version: 1.999.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
clone_depth: 1
# scripts that run after cloning repository
install:  
  - git.exe submodule update --init --recursive
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  BinTrayUserName: aqoviabot
  BinTrayApiKey:
    secure: 2IYE5snVeQL6iDa1mJ0z38R6mgymmr5R5lP4PkvIlaFIdfxv6sfeoSs8+hl0ELS1
build:
  project: MigraDoc\src\BuildAll-MigraDoc.sln 
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
# scripts to run after build
configuration: Release
after_build:
   - NuGet.exe pack PDFsharp-MigraDoc-GDI.nuspec -Version %APPVEYOR_BUILD_VERSION%
deploy_script:
- ps: "write-host branch is $env:APPVEYOR_REPO_BRANCH\n if ($env:APPVEYOR_REPO_BRANCH -eq \"forkMaster\")\n{\n write-host publishing  \n    $repo = \"https://api.bintray.com/nuget/aqovia/NuGetOSS\"\n\n    nuget sources Add -Name Bintray -Source $repo -UserName $env:BinTrayUserName -Password $env:BinTrayApiKey\n    nuget setapikey \"$($env:BinTrayUserName):$($env:BinTrayApiKey)\" -Source Bintray\n\n    $packages = Get-ChildItem -Recurse -Filter *.nupkg . \n    ForEach ($package in $packages)\n    {\n write-host Publishing $package.FullName \n      nuget push $package.FullName -Source $repo\n    }\n}"